### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/FlatUI#1]
Выложи плиз скриншоты с настройками которые ты использовала для PerfectPixel (в инверсии).

**Comment by kuvshinova-am** [comment]
![fireshot capture 4 - index - http___localhost_9000_](https://user-images.githubusercontent.com/24365265/42985816-388fa16c-8c1d-11e8-8cd9-1c579c142920.png)
настройки теже что и в проекте

**Comment by kuvshinova-am** [comment]
замечания будут?

**Comment by ValentinAlexandrovich** [comment]
Да.  
Общее: Не те шрифты.
1) Кнопки: шрифт смещен. На макете видно, что риппл эффект не ограничивается размерами кнопки.
2) Стрелки: толщина рамки
3) Проценты: отцентровать цифры
4) User profile: высота иконок соц сетей
5) Events: высота кнопки
6) Календарь: высота ячеек
7) Сообщения: позиционирование имени, иконки фотика, кнопка текст и ее высота.

**Comment by ValentinAlexandrovich** [comment]
Ограничен размерами кнопки, на макете по другому.

**Comment by Geksanit** [comment]
это мелочь

**Comment by ValentinAlexandrovich** [comment]
Нужно подправить)
