### ISSUE TITLE
gh pages

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/FlatUI#12]
Подправь UI kit (там похоже не подключаются стили), чтобы можно было проверить функциональность.

**Comment by kuvshinova-am** [comment]
у меня все работает

**Comment by ValentinAlexandrovich** [comment]
Да теперь все ок. Подправь только шрифты и толщину текста, визуально отличаются от тех что в макете. 
![2018-08-25 08-50-16](https://user-images.githubusercontent.com/31854808/44613823-016d8f80-a844-11e8-85bb-00a0a3374117.png)
![2018-08-25 08-50-20](https://user-images.githubusercontent.com/31854808/44613825-03cfe980-a844-11e8-951f-6e9a4d8444b0.png)
![2018-08-25 08-50-27](https://user-images.githubusercontent.com/31854808/44613827-06324380-a844-11e8-982b-a01eed2e9b62.png)
![2018-08-25 08-50-37](https://user-images.githubusercontent.com/31854808/44613828-08949d80-a844-11e8-9a3c-1ade3848645b.png)

**Comment by ValentinAlexandrovich** [comment]
а причем тут localhost и gh-pages? В консоле вот что выпадает 
bundle.js:42 GET https://kuvshinova-am.github.io/fonts/lato-bold.woff 404 ()
Подправить, чтобы работало, что еще тут делать))
