### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/FlatUI#13]
Верстка и UI также должны быть адаптивными. По поводу макета сайта, у тебя хорошая основа, осталось подправить наполнение(к примеру разнеси блоки с помощью гридов либо флексов, чтобы он был более похож на сайт, добавь поясняющей информации, небольшой баг стрелки внизу не работают, и продемонстрируй изменяемость компонент на своих страничках)

**Comment by kuvshinova-am** [comment]
**(к примеру разнеси блоки с помощью гридов либо флексов, чтобы он был более похож на сайт**
по моему он и так похож на сайт. напиши пожалуйста точнее что ты хочешь что бы я сделала.(непонятно).
**добавь поясняющей информаци**
**продемонстрируй изменяемость компонент на своих страничках**
что ты имеешь ввиду?

**Comment by ValentinAlexandrovich** [comment]
Да, у меня по этому макету больше нет замечаний.
Подправь ишью со шрифтами, и эти:
1) Вот здесь https://kuvshinova-am.github.io/FlatUI/build/news-and-events.html
Задать различные ивенты и новости. Остальное на твое усмотрение.
2) Почему здесь пропадает первое значение у слайдера?
https://kuvshinova-am.github.io/FlatUI/build/home-page-2.html

**Comment by ValentinAlexandrovich** [comment]
3) responsive 
![2018-08-28 10-48-40](https://user-images.githubusercontent.com/31854808/44699994-fa978480-aab0-11e8-8ecc-67417ecd51d6.png)
