### ISSUE TITLE
Передача массива опций

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#15]
```
+button-container([{title: 'standard buttons'}])
+arrow-container([{title: 'arrow buttons'}])
```
А по какой причине ты так сделала? Т.е. передачу опций массивом объектов. Почему не просто одним объектом?

**Comment by chmnkh** [comment]
Причем везде такая штука, насколько я вижу.

**Comment by kuvshinova-am** [comment]
т.е. сделать так?
+button-container({title: 'standard buttons'})
+arrow-container({title: 'arrow buttons'})

**Comment by chmnkh** [comment]
да, конечно

**Comment by chmnkh** [comment]
а почему option-то? ты же не одну опцию передаешь)

**Comment by chmnkh** [comment]
```
mixin arrow(options)
    each option in options
```
Тут и еще в куче подобных блоков эта штука осталась, тоже убрать надо. У тебя каждый миксин должен один блок рисовать, если тебе нужно несколько одинаковых блоков рисовать, вызывай миксин в цикле несколько раз. Как правило редко возникает необходимость сразу несколько одинаковых блоков подряд сделать, каждый раз передавать массив - это ж неудобно.
Когда будешь это делать, сделай при передаче опций этих деструктуризацию как в первом макете делала (и там где уже передается не массив тоже сделай деструктуризацию вместо option).
