### ISSUE TITLE
Элементы должны находиться внутри блоков, а не наоборот

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#16]
```
 form.stages-slider__form
     input.stages-slider.js-stages-slider(type= option.type)
```
```
form.discrete-slider__form
     input.discrete-slider.js-discrete-slider(value= option.value)
```

**Comment by chmnkh** [comment]
И тут же стоит задуматься, нужно ли тебе вообще делать слайдер сразу формой самостоятельной. В реальной жизни ты скорее будешь его на какую-то форму добавлять, а не сабмитить один лишь слайдер по ентеру.

**Comment by kuvshinova-am** [comment]
**Stages, кстати, не стоит слайдером обзывать, это не слайдер :)**
ок.
**И тут же стоит задуматься, нужно ли тебе вообще делать слайдер сразу формой самостоятельной. В реальной жизни ты скорее будешь его на какую-то форму добавлять, а не сабмитить один лишь слайдер по ентеру.**
это вытекло из правила что все импуты должны быть в form. изначально так не было.
т.е. просто удалить форму и будет все ок?

**Comment by chmnkh** [comment]
> т.е. просто удалить форму и будет все ок?

да
По поводу правила поясню: там подразумевалось то, что у тебя инпуты должны быть в какой-то форме всегда, потому что они на сервер отправляться будут. Инпут оборачивать в форму, как ты сделала, нужно только тогда, когда он у тебя самодостаточен и ты его не планируешь в другую форму вставлять. Форму в форму вкладывать нельзя.

**Comment by kuvshinova-am** [comment]
понятно
