### ISSUE TITLE
Избавиться от неиспользуемых модификаторов

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#17]
.form-container__column_left и .form-container__column_right не имеют никаких стилей вообще.
Дополнительно: если у тебя на элементе висит модификатор то на нем будет как минимум 2 класса всегда: класс элемента и класс элемента с модификатором. Т.о. у тебя будут применены стили для элемента + стили для модификатора, а не только для модификатора.

**Comment by chmnkh** [comment]
В рамках этого же ишью можешь блоку form название получше дать, форм то много разных может быть.

**Comment by chmnkh** [comment]
Раз уж я здесь за form зацепился:
```
.form__valid
   .form__valid-message
```
Такие сокращения не делай, потому что valid - это другое слово (не validation) и часть речи другая, название элемента form__valid - странное, а form__valid-message вообще запутать может.

**Comment by kuvshinova-am** [comment]
**.form-container__column_left и .form-container__column_right не имеют никаких стилей вообще.**
но при этом они все равно играю роль в оформлении.
если их убрать то .tick-container поедет. он будет находиться не под .toggle-container как сейчас, а рядом.
**В рамках этого же ишью можешь блоку form название получше дать, форм то много разных может быть.**
.message-form подойдет?

**Comment by chmnkh** [comment]
ну я же не говорю совсем убирать элементы, нужно просто имя класса другое сделать, модификаторы ведь определенную цель выполняют
message-form подойдет

**Comment by kuvshinova-am** [comment]
так подойдет:
            .form-container__column
                +message-form([{
                    textName: 'Your Name',
                    textEmail: 'Your Email', 
                    textMessage: 'Your Message',
                    colorButton: 'green',
                    sizeButton: 'big',
                    typeButton: 'button',
                    textButton: 'submit'
                }])
            .form-container__column
                +toggle-container({title: 'toggles'})
                +tick-container({title: 'tick boxes'})

**Comment by chmnkh** [comment]
да
