### ISSUE TITLE
функциональность ui

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/FlatUI#2]
Слайдеры: при смещении слайдера на значения от 93 до 100 , ползунок перемещается, но циферблат застывает на месте. Второй слайдер должен быть дискретным. 
Формы:  странное поведение формы Your Name, сделай чтобы работал регэксп при вводе букв thanks, при вводе цифр false.
Toggles: не работает первый переключатель
Tickboxes: не работает второй переключатель
Search forms: c первой формой при вводе текста происходит смещение
DropDown: странное поведение при нажатии на нижний левый или правый край значка выпадания списка.
Messaging: сделать поле для ввода на textarea не div.
Календарь: при нажатии кнопки today не работает изменения числа(в шапке календаря), выбранное число должно иметь выделенное цветом ячейку.

Пожелания(выполнение на твое усмотрение):  
DropDown, визуально разделить опшины для селекта, выделять цветом выбираемый.
Search form, сделать ввод текста а при нажатии на икону поиска чтобы выводилась надпись о том что ничего не найдено, при повторном клике на поле опять появлялась возможность ввода текста.

**Comment by Znack** [comment]
> Формы: странное поведение формы Your Name, сделай чтобы работал регэксп при вводе букв thanks, при вводе цифр false.

Вот это кстати тоже необязательно, на усмотрение. Хотя тут довольно просто добавить :)
