### ISSUE TITLE
Имена блоков и директорий должны совпадать

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#20]
search и typeahead, например

**Comment by kuvshinova-am** [comment]
не могу изменить typeahead на search т.к. плагин видимо зависит от имени. меняла, перестало работать.

**Comment by kuvshinova-am** [comment]
я сделала, но для этого пришло править плагин. что не есть хорошо.

**Comment by chmnkh** [comment]
плагин править точно не нужно
потыкайся в разные комбинации классов, может либе нужны какие-то конкретные классы для поведения, а для стилей, например, ты можешь свои классы оставить, да и как минимум обернуть все в блок с именем search всегда можно

**Comment by kuvshinova-am** [comment]
ок, тогда мне кажеться что самый приемлемый вариант это сделать и свои классы и оставить те что нужны для плагина. А для плагина они нужны потому что они там используються как константы.
![fireshot capture 135 - jquery typeahead search confi_ - http___www runningcoder org_jquerytypeahead_](https://user-images.githubusercontent.com/24365265/45075799-81cca400-b112-11e8-8016-f9160ddb0fec.png)
вот такой вариант подойдет?
![screenshot from 2018-09-05 13-49-41](https://user-images.githubusercontent.com/24365265/45075893-bb051400-b112-11e8-8797-a4a55e95d929.png)

**Comment by chmnkh** [comment]
Так это дефолтный конфиг и это можно при инициализации переопределить, как я понимаю, используя как раз поле selector в опциях, написав туда свои классы.
