### ISSUE TITLE
Стили vendor и стили блоков

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#21]
Не нужно выносить стили блоков, когда ты какие-то либы используешь, куда-то в папку не-блока. Все стили блоков должны быть в рамках этих блоков. Тут несколько проблем:
1) если разные стили для блоков лежат в разных местах, либо вообще все стили лежат в какой-то другой папке, это сразу же вводит путаницу;
2) когда ты определяешь стили для либовских классов глобально, в отрыве от блока, ты сразу же рискуешь столкнуться с тем, что ты захочешь ту же либу для другого блока использовать, а там уже все стили определены и печаль.

Так что если тебе нужно стили для вендорных классов определить, то тут два варианта:
1) либо ты через вложенный селектор делаешь, и тогда у тебя стили будут уже не глобальные, а в рамках блока:
```
.some-block-name
     .vendor-class
     .........
```
2) либо, если у тебя есть такая возможность, свои классы пишешь и с ними работаешь.

**Comment by kuvshinova-am** [comment]
**Не нужно выносить стили блоков, когда ты какие-то либы используешь, куда-то в папку не-блока. Все стили блоков должны быть в рамках этих блоков.**
Я с сергеем обсуждала этот момент, по поводу вендорских стилий и их несоответсвия хорошим практикам. Он сказал выносить вендоры в одельную папку вне src

**Comment by chmnkh** [comment]
Попросил мне переписку эту показать. Там речь о том была, что у тебя отдельно будут лежать вендорные файлы и твои сорцы, а не о том, что вендорные стили нужно где-то отдельно от блока переопределять. Сергей тебе писал: 

> Обычно код твоего проекта лежит в папке src, а код таких либ в vendor, и там можно не по стандартам код держать

Тут речь именно о том, что _код либы_ лежит отдельно, и вопрос ты ставила о том, что у тебя вендорные стили не по БЭМу, что с ними делать. Тебе и ответили, что твои сорцы - отдельно, либа - отдельно. А как уже переопределить часть стилей, чтобы они соответствовали макету, я тебе выше написал, и почему то, как у тебя это сделано сейчас - плохо, тоже)

**Comment by chmnkh** [comment]
Да, это норм.
В идеале было бы хорошо, конечно, полностью свои классы написать и без вложенных селекторов обойтись, как на скрине, но далеко не все либы позволяют так сделать. Дэйтпикер, который ты юзаешь, как раз не позволяет этого сделать, насколько я помню, поэтому тут только так, как на скрине сделать остается.
