### ISSUE TITLE
Блоки не должны содержать стили других блоков

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/FlatUI#30]
Пример: discrete-slider.styl
```
.sliders-container__wrap
  .slider-container
    margin-left 6.5rem
```
Там еще ниже есть какие-то классы, но это от либы я так понял. А вот что тут делает тобой написанный блок, а тем более обернутый в свой элемент - не понятно)

**Comment by kuvshinova-am** [comment]
в ветке 13-responsive я уже переделала этот слайдер, там все правильно.
